# FIXME zapravo je https://www.novahrvatskabanka.hr/gradjani/stednja-i-ulaganje/in-stednja/ povoljnija, ali moramo raditi rucno izracun...
return best_kamata_html_mpp ('https://www.novahrvatskabanka.hr/gradjani/stednja-i-ulaganje/happy-stednja/', undef, 'EKS iznosi\s+', '\s*\%');
